# Generated by Django 5.1.2 on 2025-09-23 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('source_message_id', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('wa_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('wa_stanza_id', models.CharField(blank=True, default='', max_length=128)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subasta_app.auction')),
            ],
            options={
                'ordering': ['auction_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('template', models.TextField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='subasta_app.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('wa_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_chat_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='subasta_app.item'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['phone'], name='subasta_app_phone_2032f1_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['wa_user_id'], name='subasta_app_wa_user_bb0beb_idx'),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='subasta_app.participant'),
        ),
        migrations.AddField(
            model_name='bid',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subasta_app.participant'),
        ),
        migrations.AddField(
            model_name='rule',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='subasta_app.auction'),
        ),
        migrations.AddField(
            model_name='auction',
            name='wa_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='subasta_app.whatsappgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('auction', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('auction', 'key')},
        ),
    ]
