# Generated by Django 5.2.7 on 2025-10-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta_app', '0002_auction_bid_item_messagetemplate_participant_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='claim_keyword',
            field=models.CharField(default='claim', max_length=50),
        ),
    ]
