# Generated by Django 5.2.7 on 2025-10-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta_app', '0003_auction_claim_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='claim_keyword',
            field=models.CharField(blank=True, default='claim', max_length=50),
        ),
    ]
